List<String> rDota2 =
[
  'Herald 1',
  'Herald 2',
  'Herald 3',
  'Herald 4',
  'Herald 5',
  'Guardian 1',
  'Guardian 2',
  'Guardian 3',
  'Guardian 4',
  'Guardian 5',
  'Crusader 1',
  'Crusader 2',
  'Crusader 3',
  'Crusader 4',
  'Crusader 5',
  'Archon 1',
  'Archon 2',
  'Archon 3',
  'Archon 4',
  'Archon 5',
  'Legend 1',
  'Legend 2',
  'Legend 3',
  'Legend 4',
  'Legend 5',
  'Ancient 1',
  'Ancient 2',
  'Ancient 3',
  'Ancient 4',
  'Ancient 5',
  'Divine 1',
  'Divine 2',
  'Divine 3',
  'Divine 4',
  'Divine 5',
];